version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  flask-app:
    build: ./flask-app
    container_name: flask-app
    image: myapp
